// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pathLength_cpp
NumericVector pathLength_cpp(DataFrame x, NumericMatrix Tree, double e, int ni);
RcppExport SEXP isofor_pathLength_cpp(SEXP xSEXP, SEXP TreeSEXP, SEXP eSEXP, SEXP niSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Tree(TreeSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type ni(niSEXP);
    rcpp_result_gen = Rcpp::wrap(pathLength_cpp(x, Tree, e, ni));
    return rcpp_result_gen;
END_RCPP
}
// nodes_cpp
IntegerVector nodes_cpp(DataFrame x, NumericMatrix Tree, double e, int ni);
RcppExport SEXP isofor_nodes_cpp(SEXP xSEXP, SEXP TreeSEXP, SEXP eSEXP, SEXP niSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Tree(TreeSEXP);
    Rcpp::traits::input_parameter< double >::type e(eSEXP);
    Rcpp::traits::input_parameter< int >::type ni(niSEXP);
    rcpp_result_gen = Rcpp::wrap(nodes_cpp(x, Tree, e, ni));
    return rcpp_result_gen;
END_RCPP
}
// predict_iForest_pathLength_cpp
NumericVector predict_iForest_pathLength_cpp(DataFrame x, List Model);
RcppExport SEXP isofor_predict_iForest_pathLength_cpp(SEXP xSEXP, SEXP ModelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type Model(ModelSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_iForest_pathLength_cpp(x, Model));
    return rcpp_result_gen;
END_RCPP
}
// predict_iForest_nodes_cpp
IntegerMatrix predict_iForest_nodes_cpp(DataFrame x, List Model);
RcppExport SEXP isofor_predict_iForest_nodes_cpp(SEXP xSEXP, SEXP ModelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type Model(ModelSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_iForest_nodes_cpp(x, Model));
    return rcpp_result_gen;
END_RCPP
}
