# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pathLength_cpp <- function(x, Tree, e, ni) {
    .Call('isofor_pathLength_cpp', PACKAGE = 'isofor', x, Tree, e, ni)
}

predict_iForest_cpp <- function(x, Model) {
    .Call('isofor_predict_iForest_cpp', PACKAGE = 'isofor', x, Model)
}

